// Mocks generated by Mockito 5.4.4 from annotations
// in gea_app/test/features/calendar/pinned_events_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fpdart/fpdart.dart' as _i2;
import 'package:gea_app/core/error/failures.dart' as _i5;
import 'package:gea_app/features/calendar/domain/entities/event.dart' as _i6;
import 'package:gea_app/features/calendar/domain/repositories/pinned_event_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PinnedEventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPinnedEventRepository extends _i1.Mock
    implements _i3.PinnedEventRepository {
  MockPinnedEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>> getPinnedEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPinnedEvents,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Event>>(
          this,
          Invocation.method(
            #getPinnedEvents,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> pinEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #pinEvent,
          [eventId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #pinEvent,
            [eventId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> unpinEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpinEvent,
          [eventId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #unpinEvent,
            [eventId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
